version: "3.8"

services:
  php:
    build: .
    container_name: php_server
    ports:
      - "2027:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html

  db:
    image: mariadb:10.11
    restart: always
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

volumes:
  db_data:
